# -*- coding: utf-8 -*-
"""easy graph rag

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19gfftoqEzMB3IhRRIzSwSuX7Kreb6wuC
"""

!pip install streamlit langgraph langgraph-checkpoint-sqlite langchain-core langchain-groq duckduckgo_search sentence-transformers python-dotenv spotipy langchain pinecone pinecone-client pinecone-text langchain-community langchain-openai faiss-cpu numpy pandas matplotlib seaborn scikit-learn requests beautifulsoup4 lxml langchain_huggingface networkx

!pip install pypdf

# -*- coding: utf-8 -*-
"""rag

Automatically generated by Colab.
"""

api_key = "pcsk_39EGLB_PC9i9y7MQo2FxSqgqdX4akFP3LPFoNqHirwHsicYqAivgQASB4bFsM9ocPY9epZ"

# ========================================
# 🌟 ADDED: Updated pip install with networkx & faiss-cpu for Graph & Caching
# ========================================
#!pip install streamlit langgraph langgraph-checkpoint-sqlite langchain-core langchain-groq duckduckgo_search sentence-transformers python-dotenv spotipy langchain pinecone pinecone-client pinecone-text langchain-community langchain-openai faiss-cpu numpy pandas matplotlib seaborn scikit-learn requests beautifulsoup4 lxml langchain_huggingface networkx

from langchain_huggingface import HuggingFaceEmbeddings
from langchain_groq import ChatGroq

# Initialize embeddings and model
embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

model = ChatGroq(
    model_name="llama-3.1-8b-instant",
    api_key='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'
)

# ========================================
# 🌟 NEW ADDITION 1: SEMANTIC CACHING CLASS 🌟
# Instead of hitting the LLM for similar questions, we use FAISS to
# check if a semantically similar question was already answered.
# ========================================
import faiss
import numpy as np
#lass matlab ek box (container). Us box ke andar hum related cheezein rakhte hain.  bag ke andr notebbok, pencil, pen
class SemanticCache:
    def __init__(self, embeddings_model, threshold=0.85):
        self.embeddings = embeddings_model
        self.threshold = threshold
        self.dim = 384  # Dimension for all-MiniLM-L6-v2
        self.index = faiss.IndexFlatIP(self.dim) # Inner product (Cosine Similarity)
        self.cache_answers = []

    def _get_vector(self, text):
        vec = np.array([self.embeddings.embed_query(text)], dtype=np.float32)
        faiss.normalize_L2(vec)
        return vec

    def get_cached_answer(self, query):
        if self.index.ntotal == 0:
            return None
        vec = self._get_vector(query)
        distances, indices = self.index.search(vec, 1)
        if distances[0][0] >= self.threshold:
            print(f"\n⚡ SEMANTIC CACHE HIT! Similarity: {distances[0][0]:.4f}")
            return self.cache_answers[indices[0][0]]
        return None

    def add_to_cache(self, query, answer):
        vec = self._get_vector(query)
        self.index.add(vec)
        self.cache_answers.append(answer)

# Initialize Cache
semantic_cache = SemanticCache(embeddings)

# ========================================
# 🌟 NEW ADDITION 2: GRAPH RAG (Knowledge Graph) CLASS 🌟
# Extracts factual entities and relationships to prevent hallucinations
# ========================================
import networkx as nx

class KnowledgeGraphRAG:
    def __init__(self, llm):
        self.llm = llm
        self.graph = nx.Graph()

    def build_graph(self, documents):
        print("\n🕸️ Building Knowledge Graph from top retrieved contexts...")
        # Strict prompt to prevent hallucination
        prompt = """
        Extract knowledge triplets from the following text.
        Format exactly as: Entity1 | Relationship | Entity2
        RULES:
        - Only extract factual information EXPLICITLY present in the text.
        - Do not hallucinate or infer outside knowledge.
        - If no clear relationships exist, output 'NONE'.
        Text: {text}
        """
        for doc in documents:
            try:
                res = self.llm.invoke(prompt.format(text=doc.page_content)).content
                for line in res.split('\n'):
                    if '|' in line:
                        parts = [p.strip() for p in line.split('|')]
                        if len(parts) == 3:
                            self.graph.add_edge(parts[0], parts[2], relation=parts[1])
            except Exception as e:
                continue
        print(f"✅ Graph built! Nodes: {self.graph.number_of_nodes()} | Edges: {self.graph.number_of_edges()}")

    def get_graph_context(self, query):
        if self.graph.number_of_nodes() == 0:
            return ""

        # Extract entities from the query
        extract_prompt = f"Extract the main keywords/entities from this query as a comma-separated list. Query: {query}"
        try:
            entities = self.llm.invoke(extract_prompt).content.split(',')
            entities = [e.strip().lower() for e in entities]
        except:
            return ""

        context_relations = []
        for ent in entities:
            for node in self.graph.nodes():
                if ent in str(node).lower() or str(node).lower() in ent:
                    neighbors = self.graph.edges(node, data=True)
                    for u, v, data in neighbors:
                        context_relations.append(f"- {u} ({data.get('relation', 'related to')}) {v}")

        context_relations = list(set(context_relations)) # Deduplicate
        if not context_relations:
            return ""

        return "==== KNOWLEDGE GRAPH RELATIONSHIPS ====\n" + "\n".join(context_relations[:15])

# Initialize Graph RAG
kg_rag = KnowledgeGraphRAG(model)


query = "what is langchain?"

# HyDE function - FIXED ✅
def hyde(query):
    prompt = f"""
Write a detailed passage that would likely appear in a document containing the answer to the user's question.

The passage should:
- Include important keywords and terminology.
- Explain the topic clearly and factually.
- Be written in an encyclopedic or technical style.
- Contain information that would help a search system find relevant documents.
- Avoid conversational language.
- Do not mention the question itself.

Question:
{query}

Passage:
"""
    llm_response = model.invoke(prompt)
    # FIXED: Extract content properly ✅
    return llm_response.content

# Get hypothetical document
hypothetical_doc = hyde(query)
print(f"HyDE Generated:\n{hypothetical_doc}\n")


# Upload and process PDF
from google.colab import files
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from pinecone_text.sparse import BM25Encoder

print("Please upload your PDF file:")
uploaded = files.upload()

pdf_filename = list(uploaded.keys())[0]
print(f"Uploaded: {pdf_filename}")

# Load PDF
loader = PyPDFLoader(pdf_filename)
documents = loader.load()
print(f"Loaded {len(documents)} pages")

# Split with metadata preservation
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=200,
    length_function=len,
)
chunks = text_splitter.split_documents(documents)
print(f"Split into {len(chunks)} chunks")

# Initialize BM25
bm25_encoder = BM25Encoder().default()
texts = [doc.page_content for doc in chunks]
bm25_encoder.fit(texts)
print("✅ BM25 Encoder fitted")


# Pinecone setup
from pinecone import Pinecone, ServerlessSpec
from langchain_community.retrievers import PineconeHybridSearchRetriever

pc = Pinecone(api_key=api_key)
index_name = "langgraph"

if index_name not in pc.list_indexes().names():
    pc.create_index(
        name=index_name,
        dimension=384,
        metric="dotproduct",
        spec=ServerlessSpec(cloud="aws", region="us-east-1")
    )

index = pc.Index(index_name)
print("✅ Pinecone Connected")

# Create and upload vectors with enhanced metadata
vectors = []
for i, (text, doc) in enumerate(zip(texts, chunks)):
    dense_vector = embeddings.embed_query(text)
    sparse_vector = bm25_encoder.encode_documents([text])[0]

    # Enhanced metadata for context construction
    vectors.append({
        "id": str(i),
        "values": dense_vector,
        "sparse_values": sparse_vector,
        "metadata": {
            "context": text,
            "page": doc.metadata.get('page', 0),  # Store page number
            "chunk_id": i,  # Store chunk position
            "source": doc.metadata.get('source', pdf_filename)
        }
    })

index.upsert(vectors=vectors)
print(index.describe_index_stats())

# Initialize retriever
retriever = PineconeHybridSearchRetriever(
    embeddings=embeddings,
    sparse_encoder=bm25_encoder,
    index=index,
    alpha=0.5,
    top_k=7  # Get more for context construction
)

# Retrieve documents
retrieved_docs = retriever.invoke(hypothetical_doc)
print(f"\n✅ Retrieved {len(retrieved_docs)} documents")

# ========================================
# CONTEXT CONSTRUCTION 🎯
# ========================================

import numpy as np
from sentence_transformers import CrossEncoder

def construct_context(retrieved_docs, top_k=3, score_threshold=0.0, max_tokens=2000):
    docs_with_metadata = []
    for doc in retrieved_docs:
        docs_with_metadata.append({
            'content': doc.page_content,
            'page': doc.metadata.get('page', 0),
            'chunk_id': doc.metadata.get('chunk_id', 0),
            'source': doc.metadata.get('source', 'unknown'),
            'score': doc.metadata.get('score', 0.0)
        })

    def filter_by_score(docs, threshold=0.0):
        if threshold <= 0.0:
            return docs
        filtered = [doc for doc in docs if doc.get('score', 0.0) >= threshold]
        return filtered

    def deduplicate(docs, threshold=0.8):
        unique_docs = []
        for doc in docs:
            is_unique = True
            for unique_doc in unique_docs:
                content1 = set(doc['content'].lower().split())
                content2 = set(unique_doc['content'].lower().split())
                if len(content1) == 0 or len(content2) == 0:
                    continue
                overlap = len(content1 & content2) / len(content1 | content2)
                if overlap > threshold:
                    is_unique = False
                    if doc.get('score', 0) > unique_doc.get('score', 0):
                        unique_docs.remove(unique_doc)
                        unique_docs.append(doc)
                    break
            if is_unique:
                unique_docs.append(doc)
        return unique_docs

    def manage_context_window(docs, max_tokens=2000):
        MAX_CHARS = max_tokens * 4
        CHUNK_MAX_CHARS = MAX_CHARS // max(len(docs), 1)
        managed_docs = []
        total_chars = 0
        for doc in docs:
            content = doc['content'].strip()
            if len(content) > CHUNK_MAX_CHARS:
                content = content[:CHUNK_MAX_CHARS]
                last_period = content.rfind('.')
                if last_period > CHUNK_MAX_CHARS * 0.5:
                    content = content[:last_period + 1]
                content = content + " [truncated]"
            if total_chars + len(content) > MAX_CHARS:
                break
            doc_copy = doc.copy()
            doc_copy['content'] = content
            managed_docs.append(doc_copy)
            total_chars += len(content)
        return managed_docs

    def balance_sources(docs, max_per_source=2):
        source_counts = {}
        balanced_docs = []
        for doc in docs:
            source = doc.get('source', 'unknown')
            count = source_counts.get(source, 0)
            if count < max_per_source:
                balanced_docs.append(doc)
                source_counts[source] = count + 1
        return balanced_docs

    def sort_by_position(docs):
        return sorted(docs, key=lambda x: (x['page'], x['chunk_id']))

    # Step 1: Score threshold filtering
    filtered_docs = filter_by_score(docs_with_metadata, threshold=score_threshold)
    # Step 2: Deduplicate
    unique_docs = deduplicate(filtered_docs, threshold=0.8)
    # Step 3: Source balancing
    balanced_docs = balance_sources(unique_docs, max_per_source=2)
    # Step 4: Take top K
    top_docs = balanced_docs[:top_k]
    # Step 5: Context window management
    managed_docs = manage_context_window(top_docs, max_tokens=max_tokens)
    # Step 6: Sort by position
    sorted_docs = sort_by_position(managed_docs)

    formatted_context = []
    for i, doc in enumerate(sorted_docs, 1):
        score_str = f"{doc['score']:.4f}" if doc.get('score', 0) > 0 else "N/A"
        source_str = doc.get('source', 'unknown')
        formatted_context.append(
            f"[Document {i} | Page {doc['page']} | Source: {source_str} | Score: {score_str}]\n{doc['content']}"
        )

    return "\n\n---\n\n".join(formatted_context), sorted_docs


# ========================================
# RERANKING with Context Construction
# ========================================

reranker = CrossEncoder('cross-encoder/ms-marco-MiniLM-L-6-v2')
doc_texts = [doc.page_content for doc in retrieved_docs]
pairs = [[hypothetical_doc, doc_text] for doc_text in doc_texts]
scores = reranker.predict(pairs)
ranked = sorted(zip(scores, retrieved_docs), key=lambda x: x[0], reverse=True)

top_docs_for_context = []
for score, doc in ranked[:5]:
    doc.metadata['score'] = float(score)
    top_docs_for_context.append(doc)

constructed_context, sorted_docs = construct_context(
    top_docs_for_context,
    top_k=3,
    score_threshold=0.0,
    max_tokens=2000
)

# ========================================
# 🌟 ADDED: Execute Graph RAG integration
# We append factual Graph data to our context
# ========================================
kg_rag.build_graph(top_docs_for_context)
graph_context = kg_rag.get_graph_context(query)

if graph_context:
    constructed_context = graph_context + "\n\n" + constructed_context


def generate_answer(query, constructed_context):
    prompt = f"""
You are an expert retrieval-augmented AI assistant.

Your task is to answer the user's question using ONLY the information provided in the retrieved context and Knowledge Graph relationships.

Rules:
1. Grounding
- Use only facts found in the context.
- Do not use outside knowledge.
- Do not infer facts that are not explicitly supported by the context.
- If the context is insufficient, state: "I don't have enough information in the provided context to answer this question."
2. Answer Quality
- Provide a complete and accurate answer.
- Combine information from multiple context passages when relevant.
- Remove redundant or repeated information.
3. Structure
- Start with a direct answer.
- Then provide supporting details.
- Use bullet points or numbered lists when helpful.
4. Handling Conflicts
- If multiple context passages contain conflicting information, mention the conflict and present both viewpoints.
5. Citations
- When source identifiers are available, cite them inline. Example: [Document 2], [Page 5].

Question:
{query}

Retrieved Context:
{constructed_context}

Answer:
"""
    response = model.invoke(prompt)
    return response.content

# ========================================
# 🌟 ADDED: Semantic Cache Execution Wrapper 🌟
# ========================================
print("\n" + "="*60)
print(f"QUERY: {query}")
print("="*60)

# Check Cache First
cached_response = semantic_cache.get_cached_answer(query)

if cached_response:
    final_answer = cached_response
else:
    # Generate final answer if not in cache
    final_answer = generate_answer(query, constructed_context)
    # Save to Cache
    semantic_cache.add_to_cache(query, final_answer)

print("\nFINAL ANSWER:")
print("="*60)
print(final_answer)
print("="*60)


# ========================================
# 🌟 ADDED: Demonstration of Semantic Caching 🌟
# ========================================
similar_query = "can you explain what langchain actually is?"
print(f"\nTesting Semantic Cache with similar query: '{similar_query}'")

cache_check = semantic_cache.get_cached_answer(similar_query)
if cache_check:
    print(f"\nSuccessfully retrieved from Cache (Bypassed LLM!):\n{cache_check}")
