# -*- coding: utf-8 -*-
"""graph rag

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13XpH1g30ZUBsfXaSYnkPLvLjq38D1gcm
"""

# 1. AUTO-FIX DEPENDENCIES (Run this cell)
# ============================================================
import os
print("📦 Upgrading PyTorch, Transformers, and Graph libraries...")
os.system("pip install -qU torch torchvision torchaudio")
os.system("pip install -qU transformers sentence-transformers")
os.system("pip install -qU langchain-core langchain-groq langchain-community langchain-pinecone langchain_huggingface langchain-text-splitters")
os.system("pip install -qU pinecone pinecone-text pypdf pyvis networkx spacy")
os.system("python -m spacy download en_core_web_sm -q")
print("✅ Installation complete.")

# ============================================================
print("🧹 Cleaning up broken installations...")
!pip uninstall -y torch torchvision torchaudio > /dev/null 2>&1

print("📦 Installing Synchronized PyTorch (CUDA 12.1)...")
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121 -q

print("📦 Installing RAG and Graph Dependencies...")
!pip install -qU transformers sentence-transformers langchain-core langchain-groq langchain-community langchain-pinecone langchain_huggingface langchain-text-splitters pinecone-client pinecone-text pypdf pyvis networkx spacy
!python -m spacy download en_core_web_sm -q
print("✅ Installation complete! Loading Pipeline")

# ============================================================
# 1. BULLETPROOF DEPENDENCY INSTALLER
# ============================================================
print("🧹 1. Uninstalling broken Audio/Video PyTorch libraries causing FFmpeg errors...")
!pip uninstall -y torchvision torchaudio torchcodec > /dev/null 2>&1

print("📦 2. Installing pure PyTorch...")
!pip install -q torch==2.4.1 --index-url https://download.pytorch.org/whl/cu121

print("📦 3. Installing Graph RAG & NLP Dependencies...")
!pip install -qU transformers sentence-transformers langchain-core langchain-groq langchain-community langchain-pinecone langchain_huggingface langchain-text-splitters pinecone-client pinecone-text pypdf pyvis networkx spacy datasets ragas
!python -m spacy download en_core_web_sm -q

print("✅ Installation complete! You can now run the main code.")

# ============================================================
# FULL GRAPH RAG PIPELINE
# ============================================================
import re
import time
import json
import logging
import pickle
from typing import Optional
from collections import defaultdict

import networkx as nx
import spacy
import matplotlib.pyplot as plt
from pyvis.network import Network
from IPython.display import display, HTML

from google.colab import files
from sentence_transformers import CrossEncoder
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from pinecone_text.sparse import BM25Encoder
from pinecone import Pinecone, ServerlessSpec
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_groq import ChatGroq
from langchain_pinecone import PineconeVectorStore
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.messages import HumanMessage, AIMessage
from langchain_core.documents import Document

# ============================================================
# LOGGING SETUP
# ============================================================
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)

# ============================================================
# 1. CONFIGURATION
# ============================================================
PINECONE_API_KEY = "pcsk_39EGLB_PC9i9y7MQo2FxSqgqdX4akFP3LPFoNqHirwHsicYqAivgQASB4bFsM9ocPY9epZ"
GROQ_API_KEY = "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"

# Index names
MAIN_INDEX_NAME       = "rag-main"
CACHE_INDEX_NAME      = "rag-cache"

# Model settings
EMBEDDING_DIM         = 384
EMBEDDING_MODEL       = "sentence-transformers/all-MiniLM-L6-v2"
LLM_MODEL             = "llama-3.1-8b-instant"

# Retrieval settings
HYBRID_ALPHA          = 0.5
TOP_K_RETRIEVE        = 7
TOP_K_RERANK          = 5
TOP_K_CONTEXT         = 3
MAX_CONTEXT_TOKENS    = 2000

# Cache settings
CACHE_SCORE_THRESHOLD = 0.92
MAX_HISTORY_TURNS     = 3

# Chunking settings
CHUNK_SIZE            = 1000
CHUNK_OVERLAP         = 200
UPSERT_BATCH_SIZE     = 100

# ── Graph RAG Configuration ──────────────────────────────────
GRAPH_TOP_K           = 5      # neighbours to fetch from graph per query entity
GRAPH_HOP_DEPTH       = 2      # how many hops to traverse from seed nodes
GRAPH_WEIGHT_THRESHOLD= 0.3    # min edge weight to follow during traversal
GRAPH_RAG_BLEND       = 0.4    # 0.0 = pure vector | 1.0 = pure graph results
GRAPH_SAVE_PATH       = "knowledge_graph.gpickle"  # persist graph to disk

# ============================================================
# 2. INITIALIZE MODELS
# ============================================================
logger.info("Initializing embedding model...")
embeddings = HuggingFaceEmbeddings(
    model_name=EMBEDDING_MODEL,
    model_kwargs={"device": "cpu"},
    encode_kwargs={"normalize_embeddings": True}
)

logger.info("Initializing LLM...")
llm = ChatGroq(
    model_name=LLM_MODEL,
    api_key=GROQ_API_KEY,
    temperature=0.1,
    max_tokens=1024
)

logger.info("Initializing cross-encoder reranker...")
reranker = CrossEncoder(
    "cross-encoder/ms-marco-MiniLM-L-6-v2",
    max_length=512
)

logger.info("Loading spaCy NLP model for entity extraction...")
nlp = spacy.load("en_core_web_sm")

# ============================================================
# 3. PINECONE SETUP
# ============================================================
pc = Pinecone(api_key=PINECONE_API_KEY)

def _wait_for_index(name: str) -> None:
    while True:
        status = pc.describe_index(name).status
        if status.get("ready", False):
            break
        logger.info(f"  Waiting for index '{name}' to be ready...")
        time.sleep(3)

def _ensure_index(name: str, dimension: int, metric: str) -> None:
    existing_names = [idx.name for idx in pc.list_indexes().indexes]
    if name not in existing_names:
        logger.info(f"Creating index '{name}' (metric={metric})...")
        pc.create_index(
            name=name,
            dimension=dimension,
            metric=metric,
            spec=ServerlessSpec(cloud="aws", region="us-east-1")
        )
        _wait_for_index(name)
        logger.info(f"Index '{name}' is ready.")
    else:
        logger.info(f"Index '{name}' already exists — skipping creation.")

_ensure_index(MAIN_INDEX_NAME, dimension=EMBEDDING_DIM, metric="dotproduct")
_ensure_index(CACHE_INDEX_NAME, dimension=EMBEDDING_DIM, metric="cosine")

main_index  = pc.Index(MAIN_INDEX_NAME)
cache_index = pc.Index(CACHE_INDEX_NAME)

logger.info(f"Main  index stats : {main_index.describe_index_stats()}")
logger.info(f"Cache index stats : {cache_index.describe_index_stats()}")

# ============================================================
# 4. SEMANTIC CACHE
# ============================================================
semantic_cache_store = PineconeVectorStore(
    index=cache_index,
    embedding=embeddings,
    text_key="query_text"
)

# ============================================================
# 5. CONDENSE CHAIN
# ============================================================
_condense_prompt = ChatPromptTemplate.from_messages([
    (
        "system",
        "You are a helpful assistant. "
        "Given the conversation history and the user's latest message, "
        "rewrite the latest message as a single fully self-contained question. "
        "Do NOT answer it. Do NOT add information that is not in the conversation. "
        "If there is no history, return the message exactly as given."
    ),
    ("placeholder", "{chat_history}"),
    ("human", "{latest_question}")
])
condense_chain = _condense_prompt | llm | StrOutputParser()

# ============================================================
# 6. KNOWLEDGE GRAPH (Graph RAG Core)
# ============================================================
class KnowledgeGraph:
    def __init__(self):
        self.graph: nx.DiGraph = nx.DiGraph()
        self.chunk_store: dict[str, Document] = {}
        self.entity_index: dict[str, set] = defaultdict(set)

    def _extract_entities(self, text: str) -> list[str]:
        doc = nlp(text[:1_000_000])
        entities = set()
        for ent in doc.ents:
            if ent.label_ in {"PERSON", "ORG", "GPE", "LOC", "PRODUCT", "EVENT", "WORK_OF_ART", "LAW", "NORP", "FAC"}:
                cleaned = ent.text.strip().lower()
                if len(cleaned) > 2:
                    entities.add(cleaned)
        for chunk in doc.noun_chunks:
            cleaned = chunk.root.lemma_.lower().strip()
            if len(cleaned) > 3 and chunk.root.pos_ in {"NOUN", "PROPN"} and not chunk.root.is_stop:
                entities.add(cleaned)
        return list(entities)

    def _extract_relations_llm(self, text: str, entities: list[str], chunk_id: str) -> list[tuple[str, str, str]]:
        if len(entities) < 2: return []
        entity_list = ", ".join(entities[:15])
        prompt = (
            "Extract factual relationships from the text below.\n"
            "Output ONLY valid JSON — a list of objects with keys: \"head\", \"relation\", \"tail\".\n"
            f"Use only entities from this list: {entity_list}\n"
            "If no clear relationships exist, return [].\n\n"
            f"Text:\n{text[:800]}\n\nJSON:"
        )
        try:
            response = llm.invoke(prompt)
            raw = response.content.strip()
            match = re.search(r"\[.*?\]", raw, re.DOTALL)
            if not match: return []
            triples = json.loads(match.group())
            valid = []
            for t in triples:
                h = str(t.get("head", "")).strip().lower()
                r = str(t.get("relation", "")).strip().lower()
                tl= str(t.get("tail", "")).strip().lower()
                if h and r and tl and h != tl: valid.append((h, r, tl))
            return valid
        except Exception as e:
            return []

    def add_chunk(self, chunk_id: str, text: str, doc: Document, use_llm_relations: bool = True) -> None:
        self.chunk_store[chunk_id] = doc
        entities = self._extract_entities(text)

        for ent in entities:
            if not self.graph.has_node(ent): self.graph.add_node(ent, chunks=set(), frequency=0)
            self.graph.nodes[ent]["chunks"].add(chunk_id)
            self.graph.nodes[ent]["frequency"] += 1
            self.entity_index[ent].add(chunk_id)

        for i, e1 in enumerate(entities):
            for e2 in entities[i + 1 :]:
                if e1 == e2: continue
                for src, dst in [(e1, e2), (e2, e1)]:
                    if self.graph.has_edge(src, dst):
                        self.graph[src][dst]["weight"] += 0.1
                        self.graph[src][dst]["chunks"].add(chunk_id)
                    else:
                        self.graph.add_edge(src, dst, weight=0.1, relation="co-occurs-with", chunks={chunk_id})

        if use_llm_relations:
            triples = self._extract_relations_llm(text, entities, chunk_id)
            for head, relation, tail in triples:
                for node in [head, tail]:
                    if not self.graph.has_node(node): self.graph.add_node(node, chunks=set(), frequency=0)
                    self.graph.nodes[node]["chunks"].add(chunk_id)
                    self.entity_index[node].add(chunk_id)

                if self.graph.has_edge(head, tail):
                    self.graph[head][tail]["weight"] = min(self.graph[head][tail]["weight"] + 0.5, 5.0)
                    self.graph[head][tail]["chunks"].add(chunk_id)
                    if relation != "co-occurs-with": self.graph[head][tail]["relation"] = relation
                else:
                    self.graph.add_edge(head, tail, weight=0.5, relation=relation, chunks={chunk_id})

    def retrieve_graph_context(self, query: str, top_k: int = GRAPH_TOP_K, hop_depth: int = GRAPH_HOP_DEPTH, weight_threshold: float = GRAPH_WEIGHT_THRESHOLD) -> list[Document]:
        if self.graph.number_of_nodes() == 0: return []

        query_entities = self._extract_entities(query)
        if not query_entities: return []

        seed_nodes = set()
        graph_nodes = set(self.graph.nodes())
        for qe in query_entities:
            if qe in graph_nodes: seed_nodes.add(qe)
            else:
                for gn in graph_nodes:
                    if qe in gn or gn in qe: seed_nodes.add(gn)

        if not seed_nodes: return []

        visited_nodes, collected_chunks, frontier = set(), set(), set(seed_nodes)

        for hop in range(hop_depth):
            next_frontier = set()
            for node in frontier:
                if node in visited_nodes: continue
                visited_nodes.add(node)
                collected_chunks.update(self.graph.nodes[node].get("chunks", set()))

                for neighbour in self.graph.successors(node):
                    edge_data = self.graph[node][neighbour]
                    if edge_data.get("weight", 0) >= weight_threshold and neighbour not in visited_nodes:
                        next_frontier.add(neighbour)
                        collected_chunks.update(edge_data.get("chunks", set()))

            frontier = next_frontier
            if not frontier: break

        chunk_scores = defaultdict(float)
        for node in visited_nodes:
            node_freq = self.graph.nodes[node].get("frequency", 1)
            for chunk_id in self.graph.nodes[node].get("chunks", set()):
                if chunk_id in collected_chunks: chunk_scores[chunk_id] += node_freq

        ranked_chunks = sorted(chunk_scores.items(), key=lambda x: x[1], reverse=True)[:top_k]
        result_docs = []
        for chunk_id, score in ranked_chunks:
            if chunk_id in self.chunk_store:
                doc = self.chunk_store[chunk_id]
                doc.metadata["graph_score"] = round(score, 4)
                doc.metadata["graph_hops"]  = hop_depth
                result_docs.append(doc)

        return result_docs

    def stats(self) -> dict:
        return {
            "nodes": self.graph.number_of_nodes(),
            "edges": self.graph.number_of_edges(),
            "chunks_indexed": len(self.chunk_store),
            "unique_entities": len(self.entity_index),
            "avg_degree": (sum(d for _, d in self.graph.degree()) / max(self.graph.number_of_nodes(), 1))
        }

    def visualize(self, max_nodes: int = 50, output_html: str = "knowledge_graph.html") -> None:
        if self.graph.number_of_nodes() == 0: return
        top_nodes = sorted(self.graph.degree(), key=lambda x: x[1], reverse=True)[:max_nodes]
        sub = self.graph.subgraph({n for n, _ in top_nodes})
        net = Network(height="600px", width="100%", directed=True, notebook=True, cdn_resources="in_line")
        for node, data in sub.nodes(data=True):
            freq = data.get("frequency", 1)
            net.add_node(node, label=node, size=min(10 + freq * 3, 40), title=f"Entity: {node}\nFrequency: {freq}\nChunks: {len(data.get('chunks', []))}")
        for src, dst, data in sub.edges(data=True):
            net.add_edge(src, dst, title=data.get("relation", "related"), value=data.get("weight", 0.1))
        net.set_options('{"physics": {"barnesHut": {"gravitationalConstant": -8000, "springLength": 150}, "minVelocity": 0.75}}')
        net.save_graph(output_html)
        display(HTML(output_html))

knowledge_graph = KnowledgeGraph()

# ============================================================
# 7. PDF INGESTION
# ============================================================
def ingest_pdf(pdf_path: str, use_llm_relations: bool = True) -> BM25Encoder:
    logger.info(f"Loading '{pdf_path}'...")
    pages = PyPDFLoader(pdf_path).load()
    chunks = RecursiveCharacterTextSplitter(chunk_size=CHUNK_SIZE, chunk_overlap=CHUNK_OVERLAP, length_function=len).split_documents(pages)

    texts = [c.page_content for c in chunks]
    bm25 = BM25Encoder()
    bm25.fit(texts)

    batch, total = [], 0
    print(f"\n📊 Building knowledge graph from {len(chunks)} chunks...")

    for i, (text, doc) in enumerate(zip(texts, chunks)):
        chunk_id = f"chunk-{i}"
        dense_vec = embeddings.embed_query(text)
        sparse_result = bm25.encode_documents([text])[0]

        batch.append({
            "id": chunk_id, "values": dense_vec,
            "sparse_values": {"indices": sparse_result["indices"], "values": sparse_result["values"]},
            "metadata": {"text": text, "page": doc.metadata.get("page", 0), "chunk_id": i, "source": doc.metadata.get("source", pdf_path)}
        })

        if len(batch) >= UPSERT_BATCH_SIZE:
            main_index.upsert(vectors=batch)
            total += len(batch)
            batch = []

        graph_doc = Document(page_content=text, metadata={"page": doc.metadata.get("page", 0), "chunk_id": i, "source": doc.metadata.get("source", pdf_path)})
        knowledge_graph.add_chunk(chunk_id=chunk_id, text=text, doc=graph_doc, use_llm_relations=(use_llm_relations and i < 30))

    if batch:
        main_index.upsert(vectors=batch)
        total += len(batch)

    return bm25

# ============================================================
# 8. HYBRID & GRAPH RETRIEVAL
# ============================================================
def hybrid_retrieve(query: str, bm25: BM25Encoder, top_k: int = TOP_K_RETRIEVE, alpha: float = HYBRID_ALPHA) -> list[Document]:
    dense_vec = embeddings.embed_query(query)
    sparse_raw = bm25.encode_queries([query])[0]
    response = main_index.query(
        vector=[v * alpha for v in dense_vec],
        sparse_vector={"indices": sparse_raw["indices"], "values": [v * (1 - alpha) for v in sparse_raw["values"]]},
        top_k=top_k, include_metadata=True
    )
    return [Document(page_content=m.metadata.get("text", ""), metadata={"page": m.metadata.get("page", 0), "chunk_id": m.metadata.get("chunk_id", 0), "source": m.metadata.get("source", "unknown"), "hybrid_score": round(m.score, 6), "retrieval": "hybrid"}) for m in response.matches]

def graph_aware_retrieve(original_query: str, hyp_doc: str, bm25: BM25Encoder) -> list[Document]:
    vector_docs = hybrid_retrieve(hyp_doc, bm25, top_k=TOP_K_RETRIEVE, alpha=HYBRID_ALPHA)
    graph_docs = knowledge_graph.retrieve_graph_context(original_query, top_k=GRAPH_TOP_K, hop_depth=GRAPH_HOP_DEPTH, weight_threshold=GRAPH_WEIGHT_THRESHOLD)

    merged = {}
    for doc in vector_docs[:int(TOP_K_RETRIEVE * (1 - GRAPH_RAG_BLEND))]:
        merged[str(doc.metadata["chunk_id"])] = doc

    for doc in graph_docs[:(TOP_K_RETRIEVE - len(merged))]:
        cid = str(doc.metadata["chunk_id"])
        if cid not in merged:
            doc.metadata["retrieval"] = "graph"
            merged[cid] = doc
        else:
            merged[cid].metadata["retrieval"] = "hybrid+graph"
            merged[cid].metadata["hybrid_score"] = merged[cid].metadata.get("hybrid_score", 0) * 1.1

    return list(merged.values())

def rerank_documents(original_query: str, docs: list[Document]) -> list[Document]:
    if not docs: return []
    scores = reranker.predict([[original_query, doc.page_content] for doc in docs])
    ranked = sorted(zip(scores, docs), key=lambda x: x[0], reverse=True)
    for score, doc in ranked[:TOP_K_RERANK]: doc.metadata["rerank_score"] = float(score)
    return [doc for _, doc in ranked[:TOP_K_RERANK]]

def construct_context(docs: list[Document]) -> str:
    sections = []
    for i, doc in enumerate(docs[:TOP_K_CONTEXT], 1):
        sections.append(f"[Chunk {i} | Page {doc.metadata.get('page', 0)} | Via {doc.metadata.get('retrieval', '')}]\n{doc.page_content[:MAX_CONTEXT_TOKENS*2]}")
    return "\n\n---\n\n".join(sections)

def generate_answer(query: str, context: str) -> str:
    prompt = f"Answer the user's question concisely using ONLY the provided context.\nCite chunks like [Chunk 1].\n\nQuestion: {query}\n\nContext:\n{context}\n\nAnswer:"
    return llm.invoke(prompt).content.strip()

def run_rag_pipeline(query: str, bm25: BM25Encoder) -> str:
    hyp_doc = llm.invoke(f"Write a short, factual passage (3-5 sentences) that directly answers this question: {query}").content.strip()
    retrieved = graph_aware_retrieve(query, hyp_doc, bm25)
    if not retrieved: return "I could not find relevant information in the uploaded document."
    reranked = rerank_documents(query, retrieved)
    context_str = construct_context(reranked)
    return generate_answer(query, context_str)

# ============================================================
# 18. RUN (Google Colab Entry Point)
# ============================================================
print("=" * 55)
print("📄 PLEASE UPLOAD YOUR PDF FILE:")
print("=" * 55)

uploaded = files.upload()
pdf_path = list(uploaded.keys())[0]

print("\n📥 Ingesting PDF into Pinecone + Knowledge Graph...")
bm25_encoder = ingest_pdf(pdf_path, use_llm_relations=True)

try:
    if input("\n🔍 Visualize knowledge graph? (yes/no): ").strip().lower() == "yes":
        knowledge_graph.visualize(max_nodes=60)
except KeyboardInterrupt: pass

print("\n" + "=" * 55)
print("🤖 GRAPH RAG CHAT STARTED (Type 'exit' to quit)")
print("=" * 55)

conversation_history = []

while True:
    try:
        user_input = input("\n👤 You: ").strip()
        if user_input.lower() in {"exit", "quit", "q"}: break
        if user_input.lower() == "clear":
            conversation_history = []
            print("🧹 History cleared.")
            continue
        if user_input.lower() == "graph":
            s = knowledge_graph.stats()
            print(f"\n📊 Graph: {s['nodes']} nodes | {s['edges']} edges | {s['chunks_indexed']} chunks")
            continue
        if not user_input: continue

        start = time.time()

        standalone = condense_chain.invoke({"chat_history": conversation_history, "latest_question": user_input}).strip() if conversation_history else user_input

        cached = semantic_cache_store.similarity_search_with_score(standalone, k=1)
        if cached and cached[0][1] >= CACHE_SCORE_THRESHOLD:
            answer = cached[0][0].metadata.get("answer", "")
            print("⚡ [CACHE HIT]")
        else:
            answer = run_rag_pipeline(standalone, bm25_encoder)
            semantic_cache_store.add_texts(texts=[standalone], metadatas=[{"answer": answer, "query_text": standalone}])

        print(f"\n🤖 Assistant:\n{answer}\n\n[⏱️ Response time: {time.time() - start:.2f}s]")

        conversation_history.extend([HumanMessage(content=user_input), AIMessage(content=answer)])
        if len(conversation_history) > MAX_HISTORY_TURNS * 2: conversation_history = conversation_history[-MAX_HISTORY_TURNS * 2:]

    except Exception as e:
        print(f"⚠️ Error: {e}")