# -*- coding: utf-8 -*-
"""new rag

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IjZfJZxBoUQns3C9pNXLmT3sgXXyauXj
"""

!pip install streamlit langgraph langgraph-checkpoint-sqlite langchain-core langchain-groq duckduckgo_search sentence-transformers python-dotenv spotipy langchain pinecone pinecone-client pinecone-text langchain-community langchain-openai faiss-cpu numpy pandas matplotlib seaborn scikit-learn requests beautifulsoup4 lxml langchain_huggingface

!pip list

!pip install pinecone

!pip install langchain-pinecone

!pip install pinecone-client --upgrade

!pip install --upgrade pinecone-client langchain-pinecone

!pip install pypdf

# -*- coding: utf-8 -*-
#!pip install streamlit langgraph langgraph-checkpoint-sqlite langchain-core langchain-groq duckduckgo_search sentence-transformers python-dotenv spotipy langchain pinecone pinecone-client pinecone-text langchain-community langchain-openai faiss-cpu numpy pandas matplotlib seaborn scikit-learn requests beautifulsoup4 lxml langchain_huggingface

import time
import numpy as np
from google.colab import files
from sentence_transformers import CrossEncoder
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from pinecone_text.sparse import BM25Encoder
from pinecone import Pinecone, ServerlessSpec
from langchain_community.retrievers import PineconeHybridSearchRetriever
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_groq import ChatGroq
from langchain_pinecone import PineconeVectorStore
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.messages import HumanMessage, AIMessage

# ========================================
# 1. INITIALIZATION & SETUP
# ========================================
PINECONE_API_KEY = "pcsk_39EGLB_PC9i9y7MQo2FxSqgqdX4akFP3LPFoNqHirwHsicYqAivgQASB4bFsM9ocPY9epZ" # <-- PUT YOUR PINECONE KEY HERE
GROQ_API_KEY = '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'

# Initialize embeddings and LLM
embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
model = ChatGroq(model_name="llama-3.1-8b-instant", api_key=GROQ_API_KEY)
reranker = CrossEncoder('cross-encoder/ms-marco-MiniLM-L-6-v2')

# Pinecone setup
pc = Pinecone(api_key=PINECONE_API_KEY)
index_name = "langgraph"

if index_name not in pc.list_indexes().names():
    pc.create_index(
        name=index_name,
        dimension=384, # Matches all-MiniLM-L6-v2
        metric="dotproduct",
        spec=ServerlessSpec(cloud="aws", region="us-east-1")
    )
index = pc.Index(index_name)
print("✅ Pinecone Connected")

# Setup Semantic Cache in Pinecone
semantic_cache = PineconeVectorStore(
    index_name=index_name,
    embedding=embeddings,
    namespace="semantic_cache",
    pinecone_api_key=PINECONE_API_KEY # <-- Crucial! Keeps cache separate from your PDF docs
)

# Setup Condense Chain for Chat History
condense_prompt = ChatPromptTemplate.from_messages([
    ("system", "Given the chat history and the user's latest message, rephrase the latest message into a standalone question without changing its meaning. If no history exists, just return the user's message."),
    ("placeholder", "{chat_history}"),
    ("user", "{latest_question}")
])
condense_chain = condense_prompt | model | StrOutputParser()


# ========================================
# 2. DOCUMENT INGESTION (PDF Upload)
# ========================================
print("\nPlease upload your PDF file:")
uploaded = files.upload()
pdf_filename = list(uploaded.keys())[0]
print(f"Uploaded: {pdf_filename}")

loader = PyPDFLoader(pdf_filename)
documents = loader.load()
print(f"Loaded {len(documents)} pages")

text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200, length_function=len)
chunks = text_splitter.split_documents(documents)
print(f"Split into {len(chunks)} chunks")

bm25_encoder = BM25Encoder().default()
texts = [doc.page_content for doc in chunks]
bm25_encoder.fit(texts)
print("✅ BM25 Encoder fitted")

vectors = []
for i, (text, doc) in enumerate(zip(texts, chunks)):
    dense_vector = embeddings.embed_query(text)
    sparse_vector = bm25_encoder.encode_documents([text])[0]
    vectors.append({
        "id": str(i),
        "values": dense_vector,
        "sparse_values": sparse_vector,
        "metadata": {
            "context": text,
            "page": doc.metadata.get('page', 0),
            "chunk_id": i,
            "source": doc.metadata.get('source', pdf_filename)
        }
    })

index.upsert(vectors=vectors)
print(index.describe_index_stats())

retriever = PineconeHybridSearchRetriever(
    embeddings=embeddings,
    sparse_encoder=bm25_encoder,
    index=index,
    alpha=0.5,
    top_k=7
)


# ========================================
# 3. CORE RAG HELPER FUNCTIONS
# ========================================
def hyde(query):
    prompt = f"""Write a detailed passage that would likely appear in a document containing the answer to the user's question. Include important keywords, explain factually, and do not mention the question itself.\nQuestion:\n{query}\nPassage:\n"""
    return model.invoke(prompt).content

def construct_context(docs_with_metadata, top_k=3, score_threshold=0.0, max_tokens=2000):
    unique_docs = []
    for doc in docs_with_metadata:
        is_unique = True
        for u_doc in unique_docs:
            c1, c2 = set(doc['content'].lower().split()), set(u_doc['content'].lower().split())
            if not c1 or not c2: continue
            if len(c1 & c2) / len(c1 | c2) > 0.8:
                is_unique = False
                if doc.get('score', 0) > u_doc.get('score', 0):
                    unique_docs.remove(u_doc)
                    unique_docs.append(doc)
                break
        if is_unique: unique_docs.append(doc)

    source_counts = {}
    balanced_docs = []
    for doc in unique_docs:
        src = doc.get('source', 'unknown')
        if source_counts.get(src, 0) < 2:
            balanced_docs.append(doc)
            source_counts[src] = source_counts.get(src, 0) + 1

    top_docs = balanced_docs[:top_k]
    sorted_docs = sorted(top_docs, key=lambda x: (x['page'], x['chunk_id']))

    formatted_context = []
    for i, doc in enumerate(sorted_docs, 1):
        formatted_context.append(f"[Document {i} | Page {doc['page']} | Source: {doc.get('source', 'unknown')}]\n{doc['content']}")

    return "\n\n---\n\n".join(formatted_context), sorted_docs

def generate_answer(query, constructed_context):
    prompt = f"""You are an expert retrieval-augmented AI assistant. Answer using ONLY the provided context.\nQuestion:\n{query}\nContext:\n{constructed_context}\nAnswer:\n"""
    return model.invoke(prompt).content


def run_core_rag_pipeline(query: str) -> str:
    print("⏳ Running Full RAG Pipeline...")
    hypothetical_doc = hyde(query)
    retrieved_docs = retriever.invoke(hypothetical_doc)

    doc_texts = [doc.page_content for doc in retrieved_docs]
    pairs = [[hypothetical_doc, text] for text in doc_texts]
    scores = reranker.predict(pairs)
    ranked = sorted(zip(scores, retrieved_docs), key=lambda x: x[0], reverse=True)

    top_docs_for_context = []
    for score, doc in ranked[:5]:
        doc.metadata['score'] = float(score)
        top_docs_for_context.append({
            'content': doc.page_content,
            'page': doc.metadata.get('page', 0),
            'chunk_id': doc.metadata.get('chunk_id', 0),
            'source': doc.metadata.get('source', 'unknown'),
            'score': float(score)
        })

    constructed_context, used_docs = construct_context(top_docs_for_context, top_k=3)
    final_answer = generate_answer(query, constructed_context)
    return final_answer


def get_cached_rag_response(chat_history: list, latest_question: str, threshold: float = 0.85) -> str:
    print("\n" + "-"*50)

    if chat_history:
        standalone_query = condense_chain.invoke({"chat_history": chat_history, "latest_question": latest_question})
    else:
        standalone_query = latest_question

    print(f"🔍 Query to System: '{standalone_query}'")

    cache_results = semantic_cache.similarity_search_with_score(standalone_query, k=1)

    if cache_results:
        matched_doc, score = cache_results[0]
        if score >= threshold:
            print(f"✅ CACHE HIT! (Score: {score:.3f}) - Skipping RAG entirely.")
            return matched_doc.metadata["answer"]

    print(f"❌ CACHE MISS! Running standard pipeline...")
    final_answer = run_core_rag_pipeline(standalone_query)

    print("💾 Saving generated answer to Pinecone Semantic Cache...")
    semantic_cache.add_texts(texts=[standalone_query], metadatas=[{"answer": final_answer}])

    return final_answer

print("✅ Setup complete! You can now run Cell 2 to start asking questions.")

# ========================================
# INTERACTIVE RAG CHAT (Run as many times as you want)
# ========================================
print("\n" + "="*50)
print("🤖 INTERACTIVE RAG CHAT")
print("Type 'exit' or 'quit' to stop.")
print("="*50)

# Initialize a fresh chat history every time you run this cell
conversation_history = []

while True:
    # 1. Get user input
    user_input = input("\n👤 You: ")

    # 2. Check if user wants to exit
    if user_input.lower() in ['exit', 'quit', 'q']:
        print("Exiting chat. Goodbye!")
        break

    # 3. Skip empty inputs
    if not user_input.strip():
        continue

    start_time = time.time()

    # 4. Get response (Cache Hit or RAG Pipeline)
    answer = get_cached_rag_response(
        chat_history=conversation_history,
        latest_question=user_input
    )

    # 5. Print the Answer and Time
    print(f"\n🤖 Assistant:\n{answer}")
    print(f"\n⏱️ Time taken: {time.time() - start_time:.2f} seconds")

    # 6. Update chat history for the next iteration
    conversation_history.append(HumanMessage(content=user_input))
    conversation_history.append(AIMessage(content=answer))

    # Keep only the last 6 messages (3 conversational turns)
    if len(conversation_history) > 6:
        conversation_history = conversation_history[-6:]

PINECONE_API_KEY  = "pcsk_39EGLB_PC9i9y7MQo2FxSqgqdX4akFP3LPFoNqHirwHsicYqAivgQASB4bFsM9ocPY9epZ"   # <-- Replace
GROQ_API_KEY      = "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"        # <-- Replace

# -*- coding: utf-8 -*-
# Production RAG Pipeline - Google Colab Version

# ============================================================
# INSTALL DEPENDENCIES (Run this cell first)
# ============================================================
# !pip install -q langchain-core langchain-groq langchain-community \
#   langchain-pinecone langchain_huggingface langchain-text-splitters \
#   sentence-transformers pinecone pinecone-text pypdf \
#   langchain-openai faiss-cpu

import os
import time
import logging
from typing import Optional

from google.colab import files
from sentence_transformers import CrossEncoder
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from pinecone_text.sparse import BM25Encoder
from pinecone import Pinecone, ServerlessSpec
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_groq import ChatGroq
from langchain_pinecone import PineconeVectorStore
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.messages import HumanMessage, AIMessage
from langchain_core.documents import Document

# ============================================================
# LOGGING SETUP
# ============================================================
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s"
)
logger = logging.getLogger(__name__)

# ============================================================
# 1. CONFIGURATION  ← Only section you need to edit
# ============================================================
PINECONE_API_KEY  = "pcsk_39EGLB_PC9i9y7MQo2FxSqgqdX4akFP3LPFoNqHirwHsicYqAivgQASB4bFsM9ocPY9epZ"   # <-- Replace
GROQ_API_KEY      = "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"        # <-- Replace

# Index names (will be auto-created if they don't exist)
MAIN_INDEX_NAME   = "rag-main"
CACHE_INDEX_NAME  = "rag-cache"

# Model settings
EMBEDDING_DIM     = 384
EMBEDDING_MODEL   = "sentence-transformers/all-MiniLM-L6-v2"
LLM_MODEL         = "llama-3.1-8b-instant"

# Retrieval settings
HYBRID_ALPHA          = 0.5    # 0.0 = sparse only | 1.0 = dense only
TOP_K_RETRIEVE        = 7      # docs fetched from Pinecone
TOP_K_RERANK          = 5      # docs kept after cross-encoder rerank
TOP_K_CONTEXT         = 3      # docs used in final prompt
MAX_CONTEXT_TOKENS    = 2000   # approximate token budget for context

# Cache settings
CACHE_SCORE_THRESHOLD = 0.92   # cosine similarity required for cache hit
MAX_HISTORY_TURNS     = 3      # rolling window of conversation turns

# Chunking settings
CHUNK_SIZE            = 1000
CHUNK_OVERLAP         = 200
UPSERT_BATCH_SIZE     = 100

# ============================================================
# 2. INITIALIZE MODELS
# ============================================================
logger.info("Initializing embedding model...")
embeddings = HuggingFaceEmbeddings(
    model_name=EMBEDDING_MODEL,
    model_kwargs={"device": "cpu"},
    encode_kwargs={"normalize_embeddings": True}  # required for cosine cache
)

logger.info("Initializing LLM...")
llm = ChatGroq(
    model_name=LLM_MODEL,
    api_key=GROQ_API_KEY,
    temperature=0.1,
    max_tokens=1024
)

logger.info("Initializing cross-encoder reranker...")
reranker = CrossEncoder(
    "cross-encoder/ms-marco-MiniLM-L-6-v2",
    max_length=512
)

# ============================================================
# 3. PINECONE SETUP
# ============================================================
pc = Pinecone(api_key=PINECONE_API_KEY)

def _wait_for_index(name: str) -> None:
    """Poll until the index reports ready status."""
    while True:
        status = pc.describe_index(name).status
        if status.get("ready", False):
            break
        logger.info(f"  Waiting for index '{name}' to be ready...")
        time.sleep(3)

def _ensure_index(name: str, dimension: int, metric: str) -> None:
    """Create a Pinecone index only if it does not already exist."""
    existing_names = [idx.name for idx in pc.list_indexes().indexes]
    if name not in existing_names:
        logger.info(f"Creating index '{name}' (metric={metric})...")
        pc.create_index(
            name=name,
            dimension=dimension,
            metric=metric,
            spec=ServerlessSpec(cloud="aws", region="us-east-1")
        )
        _wait_for_index(name)
        logger.info(f"Index '{name}' is ready.")
    else:
        logger.info(f"Index '{name}' already exists — skipping creation.")

# Main index: dotproduct is REQUIRED for Pinecone hybrid (dense+sparse) search
_ensure_index(MAIN_INDEX_NAME, dimension=EMBEDDING_DIM, metric="dotproduct")

# Cache index: cosine for pure dense similarity lookup
_ensure_index(CACHE_INDEX_NAME, dimension=EMBEDDING_DIM, metric="cosine")

main_index  = pc.Index(MAIN_INDEX_NAME)
cache_index = pc.Index(CACHE_INDEX_NAME)

logger.info(f"Main  index stats : {main_index.describe_index_stats()}")
logger.info(f"Cache index stats : {cache_index.describe_index_stats()}")

# ============================================================
# 4. SEMANTIC CACHE  (separate cosine index)
# ============================================================
# text_key="query_text" tells PineconeVectorStore which metadata
# field holds the text that was embedded — used for inspection only.
semantic_cache_store = PineconeVectorStore(
    index=cache_index,
    embedding=embeddings,
    text_key="query_text"
)

# ============================================================
# 5. CONDENSE CHAIN  (multi-turn history → standalone question)
# ============================================================
_condense_prompt = ChatPromptTemplate.from_messages([
    (
        "system",
        "You are a helpful assistant. "
        "Given the conversation history and the user's latest message, "
        "rewrite the latest message as a single fully self-contained question. "
        "Do NOT answer it. Do NOT add information that is not in the conversation. "
        "If there is no history, return the message exactly as given."
    ),
    ("placeholder", "{chat_history}"),
    ("human", "{latest_question}")
])
condense_chain = _condense_prompt | llm | StrOutputParser()

# ============================================================
# 6. PDF INGESTION  → returns fitted BM25Encoder
# ============================================================
def ingest_pdf(pdf_path: str) -> BM25Encoder:
    """
    Load PDF → chunk → embed (dense + sparse) → upsert to Pinecone.
    Returns the fitted BM25Encoder needed at query time.
    """
    logger.info(f"Loading '{pdf_path}'...")
    loader    = PyPDFLoader(pdf_path)
    pages     = loader.load()
    logger.info(f"  Pages : {len(pages)}")

    splitter = RecursiveCharacterTextSplitter(
        chunk_size=CHUNK_SIZE,
        chunk_overlap=CHUNK_OVERLAP,
        length_function=len
    )
    chunks = splitter.split_documents(pages)
    logger.info(f"  Chunks: {len(chunks)}")

    texts = [c.page_content for c in chunks]

    # Fit BM25 on the full corpus
    bm25 = BM25Encoder()
    bm25.fit(texts)
    logger.info("  BM25 fitted.")

    # Build vectors and upsert in batches
    batch   = []
    total   = 0

    for i, (text, doc) in enumerate(zip(texts, chunks)):
        dense_vec     = embeddings.embed_query(text)
        sparse_result = bm25.encode_documents([text])[0]  # dict: {indices, values}

        batch.append({
            "id"    : f"chunk-{i}",
            "values": dense_vec,
            "sparse_values": {
                "indices": sparse_result["indices"],
                "values" : sparse_result["values"]
            },
            "metadata": {
                "text"    : text,                              # retrieved at query time
                "page"    : doc.metadata.get("page", 0),
                "chunk_id": i,
                "source"  : doc.metadata.get("source", pdf_path)
            }
        })

        if len(batch) >= UPSERT_BATCH_SIZE:
            main_index.upsert(vectors=batch)
            total += len(batch)
            logger.info(f"  Upserted {total}/{len(chunks)} chunks...")
            batch = []

    if batch:
        main_index.upsert(vectors=batch)
        total += len(batch)

    logger.info(f"  Done. Total upserted: {total} chunks.")
    logger.info(f"  Index stats: {main_index.describe_index_stats()}")
    return bm25

# ============================================================
# 7. HYBRID RETRIEVAL  (dense + sparse via Pinecone query API)
# ============================================================
def hybrid_retrieve(
    query: str,
    bm25: BM25Encoder,
    top_k: int = TOP_K_RETRIEVE,
    alpha: float = HYBRID_ALPHA
) -> list[Document]:
    """
    alpha = 1.0  →  pure dense
    alpha = 0.0  →  pure sparse (BM25)
    alpha = 0.5  →  balanced hybrid  ← default
    """
    # Dense embedding
    dense_vec = embeddings.embed_query(query)

    # Sparse BM25 encoding  (encode_queries for query-time, not encode_documents)
    sparse_raw = bm25.encode_queries([query])[0]
    sparse_vec = {
        "indices": sparse_raw["indices"],
        "values" : sparse_raw["values"]
    }

    # Scale both sides
    scaled_dense  = [v * alpha       for v in dense_vec]
    scaled_sparse = {
        "indices": sparse_vec["indices"],
        "values" : [v * (1 - alpha) for v in sparse_vec["values"]]
    }

    response = main_index.query(
        vector=scaled_dense,
        sparse_vector=scaled_sparse,
        top_k=top_k,
        include_metadata=True
    )

    docs = []
    for match in response.matches:
        meta = match.metadata or {}
        docs.append(Document(
            page_content=meta.get("text", ""),
            metadata={
                "page"        : meta.get("page", 0),
                "chunk_id"    : meta.get("chunk_id", 0),
                "source"      : meta.get("source", "unknown"),
                "hybrid_score": round(match.score, 6)
            }
        ))

    logger.info(f"  Hybrid search returned {len(docs)} docs.")
    return docs

# ============================================================
# 8. HyDE  (Hypothetical Document Embedding)
# ============================================================
_HYDE_PROMPT = (
    "You are an expert technical writer.\n"
    "Write a short, factual passage (3-5 sentences) that directly answers "
    "the question below. Use precise domain terminology. "
    "Write in third person. Do NOT mention the question itself.\n\n"
    "Question: {query}\n\n"
    "Passage:"
)

def generate_hypothetical_doc(query: str) -> str:
    """Expand the query into a hypothetical document for better recall."""
    response = llm.invoke(_HYDE_PROMPT.format(query=query))
    hyp_doc  = response.content.strip()
    logger.info(f"  HyDE doc: {hyp_doc[:120]}...")
    return hyp_doc

# ============================================================
# 9. RERANKING  (cross-encoder on ORIGINAL query)
# ============================================================
def rerank_documents(
    original_query: str,
    docs: list[Document],
    top_k: int = TOP_K_RERANK
) -> list[Document]:
    """
    Score each doc against the ORIGINAL user query (not HyDE).
    HyDE is only used for retrieval recall — never for relevance scoring.
    """
    if not docs:
        return []

    pairs  = [[original_query, doc.page_content] for doc in docs]
    scores = reranker.predict(pairs)                        # numpy array

    ranked = sorted(zip(scores, docs), key=lambda x: x[0], reverse=True)

    result = []
    for score, doc in ranked[:top_k]:
        doc.metadata["rerank_score"] = float(score)
        result.append(doc)

    logger.info(
        f"  Reranked {len(docs)} → top {len(result)} "
        f"(best score: {result[0].metadata['rerank_score']:.4f})"
    )
    return result

# ============================================================
# 10. CONTEXT CONSTRUCTION
# ============================================================
def _jaccard(a: str, b: str) -> float:
    sa, sb = set(a.lower().split()), set(b.lower().split())
    if not sa or not sb:
        return 0.0
    return len(sa & sb) / len(sa | sb)

def _deduplicate(docs: list[dict], threshold: float = 0.85) -> list[dict]:
    """Remove near-duplicate chunks; keep the one with the higher rerank score."""
    unique: list[dict] = []
    for doc in docs:
        duplicate = False
        for u in unique:
            if _jaccard(doc["content"], u["content"]) > threshold:
                if doc["rerank_score"] > u["rerank_score"]:
                    unique.remove(u)
                    unique.append(doc)
                duplicate = True
                break
        if not duplicate:
            unique.append(doc)
    return unique

def construct_context(
    docs: list[Document],
    top_k: int = TOP_K_CONTEXT,
    max_tokens: int = MAX_CONTEXT_TOKENS
) -> tuple[str, list[dict]]:
    """
    Pipeline:
      1. Convert docs to dicts
      2. Deduplicate (Jaccard)
      3. Trim to top_k
      4. Sort by document position (page → chunk)
      5. Truncate each chunk to stay within token budget
      6. Format into a readable string

    Returns (context_string, list_of_doc_dicts).
    """
    MAX_CHARS     = max_tokens * 4
    CHARS_PER_DOC = MAX_CHARS // max(top_k, 1)

    doc_dicts = [
        {
            "content"     : doc.page_content.strip(),
            "page"        : doc.metadata.get("page", 0),
            "chunk_id"    : doc.metadata.get("chunk_id", 0),
            "source"      : doc.metadata.get("source", "unknown"),
            "rerank_score": doc.metadata.get("rerank_score", 0.0),
            "hybrid_score": doc.metadata.get("hybrid_score", 0.0)
        }
        for doc in docs
    ]

    doc_dicts = _deduplicate(doc_dicts, threshold=0.85)
    doc_dicts = doc_dicts[:top_k]

    # Sort by reading order
    doc_dicts.sort(key=lambda x: (x["page"], x["chunk_id"]))

    # Truncate to budget
    final, total_chars = [], 0
    for doc in doc_dicts:
        content = doc["content"]
        if len(content) > CHARS_PER_DOC:
            content = content[:CHARS_PER_DOC]
            last_dot = content.rfind(".")
            if last_dot > CHARS_PER_DOC * 0.5:
                content = content[: last_dot + 1]
            content += " [truncated]"

        if total_chars + len(content) > MAX_CHARS:
            logger.info("  Context budget reached — stopping early.")
            break

        doc["content"] = content
        final.append(doc)
        total_chars += len(content)

    # Format
    sections = []
    for i, doc in enumerate(final, 1):
        sections.append(
            f"[Chunk {i} | Page {doc['page']} | "
            f"Rerank: {doc['rerank_score']:.4f} | "
            f"Source: {doc['source']}]\n"
            f"{doc['content']}"
        )

    context_str = "\n\n---\n\n".join(sections)
    logger.info(
        f"  Context: {len(final)} chunks, "
        f"~{total_chars} chars (~{total_chars // 4} tokens)."
    )
    return context_str, final

# ============================================================
# 11. ANSWER GENERATION
# ============================================================
_ANSWER_PROMPT = """\
You are an expert AI assistant. Answer the user's question using ONLY \
the information in the retrieved context below.

Rules:
- Be concise and factually precise.
- Cite chunk numbers when referencing specific facts, e.g. [Chunk 2].
- If the context does not contain sufficient information, respond with:
  "I could not find a complete answer in the provided documents."
- Never fabricate or infer information not present in the context.

Question:
{query}

Retrieved Context:
{context}

Answer:"""

def generate_answer(query: str, context: str) -> str:
    response = llm.invoke(_ANSWER_PROMPT.format(query=query, context=context))
    return response.content.strip()

# ============================================================
# 12. FULL RAG PIPELINE
# ============================================================
def run_rag_pipeline(query: str, bm25: BM25Encoder) -> str:
    """
    HyDE → Hybrid Retrieve → Rerank (original query) → Context → Answer
    """
    logger.info("─── RAG PIPELINE START ───")

    # 1. Generate hypothetical document (expands vocab for retrieval)
    hyp_doc = generate_hypothetical_doc(query)

    # 2. Hybrid retrieve using HyDE doc (better recall)
    retrieved = hybrid_retrieve(hyp_doc, bm25, top_k=TOP_K_RETRIEVE, alpha=HYBRID_ALPHA)

    if not retrieved:
        logger.warning("No documents retrieved from Pinecone.")
        return "I could not find relevant information in the uploaded document."

    # 3. Rerank using ORIGINAL query (accurate relevance scoring)
    reranked = rerank_documents(query, retrieved, top_k=TOP_K_RERANK)

    # 4. Build context string
    context_str, _ = construct_context(reranked, top_k=TOP_K_CONTEXT, max_tokens=MAX_CONTEXT_TOKENS)

    # 5. Generate grounded answer
    answer = generate_answer(query, context_str)

    logger.info("─── RAG PIPELINE END ───")
    return answer

# ============================================================
# 13. SEMANTIC CACHE  (lookup & store)
# ============================================================
def cache_lookup(query: str) -> Optional[str]:
    """
    Return cached answer if a sufficiently similar query exists.
    With normalize_embeddings=True + cosine index, score ∈ [0, 1].
    Higher score = more similar.
    """
    try:
        results = semantic_cache_store.similarity_search_with_score(query, k=1)
        if not results:
            logger.info("  Cache: empty.")
            return None

        matched_doc, score = results[0]
        logger.info(f"  Cache score: {score:.4f}  (threshold: {CACHE_SCORE_THRESHOLD})")

        if score >= CACHE_SCORE_THRESHOLD:
            answer = matched_doc.metadata.get("answer", "")
            if answer:
                logger.info("  CACHE HIT ✅")
                return answer

        logger.info("  CACHE MISS ❌")
        return None

    except Exception as e:
        logger.error(f"Cache lookup error: {e}")
        return None  # Fail open: proceed to full pipeline

def cache_store(query: str, answer: str) -> None:
    """Persist query-answer pair to the semantic cache index."""
    try:
        semantic_cache_store.add_texts(
            texts=[query],
            metadatas=[{
                "answer"    : answer,
                "query_text": query,
                "timestamp" : time.time()
            }]
        )
        logger.info("  Answer stored in cache ✅")
    except Exception as e:
        logger.error(f"Cache store error: {e}")

# ============================================================
# 14. CONDENSE QUESTION
# ============================================================
def condense_question(chat_history: list, latest_question: str) -> str:
    """Rephrase latest_question into a standalone question using history."""
    if not chat_history:
        return latest_question
    try:
        result = condense_chain.invoke({
            "chat_history"   : chat_history,
            "latest_question": latest_question
        })
        standalone = result.strip()
        logger.info(f"  Condensed → '{standalone}'")
        return standalone
    except Exception as e:
        logger.error(f"Condense chain error: {e}. Using original question.")
        return latest_question

# ============================================================
# 15. MAIN CHAT FUNCTION
# ============================================================
def chat(user_message: str, chat_history: list, bm25: BM25Encoder) -> str:
    """
    Single-turn entry point.
    1. Condense with history
    2. Cache lookup
    3. Full RAG if miss
    4. Cache store
    5. Return answer
    """
    print("\n" + "─" * 55)

    standalone = condense_question(chat_history, user_message)

    # Cache check
    cached = cache_lookup(standalone)
    if cached:
        print(f"⚡ [CACHE HIT] (threshold ≥ {CACHE_SCORE_THRESHOLD})")
        return cached

    # Full pipeline
    answer = run_rag_pipeline(standalone, bm25)

    # Persist to cache
    cache_store(standalone, answer)

    return answer

# ============================================================
# 16.  RUN  (Google Colab entry point)
# ============================================================

# ── Step A: Upload PDF ──────────────────────────────────────
print("=" * 55)
print("📄 Please upload your PDF file:")
print("=" * 55)

uploaded = files.upload()   # Opens Colab file-picker dialog

if not uploaded:
    raise RuntimeError("No file was uploaded. Please re-run the cell and upload a PDF.")

pdf_path = list(uploaded.keys())[0]
print(f"\n✅ Uploaded: '{pdf_path}'")

# Verify it is actually a PDF by checking the magic bytes
with open(pdf_path, "rb") as f:
    header = f.read(5)

if header != b"%PDF-":
    raise ValueError(
        f"'{pdf_path}' does not appear to be a valid PDF file. "
        f"First bytes: {header}"
    )

# ── Step B: Ingest PDF into Pinecone ────────────────────────
print("\n📥 Ingesting PDF into Pinecone...")
bm25_encoder = ingest_pdf(pdf_path)
print("✅ Ingestion complete.")

# ── Step C: Interactive chat loop ───────────────────────────
print("\n" + "=" * 55)
print("🤖  PRODUCTION RAG CHAT  (Google Colab)")
print("    Commands: 'exit' → quit | 'clear' → reset history")
print("=" * 55)

conversation_history: list = []

while True:
    try:
        user_input = input("\n👤 You: ").strip()
    except (EOFError, KeyboardInterrupt):
        print("\n⚠️  Interrupted. Exiting.")
        break

    # Empty input — just loop again
    if not user_input:
        continue

    # Exit commands
    if user_input.lower() in {"exit", "quit", "q"}:
        print("👋 Goodbye!")
        break

    # Clear history command
    if user_input.lower() == "clear":
        conversation_history = []
        print("🧹 Conversation history cleared.")
        continue

    # ── Get answer ──────────────────────────────────────────
    start = time.time()

    try:
        answer = chat(
            user_message=user_input,
            chat_history=conversation_history,
            bm25=bm25_encoder
        )
    except Exception as e:
        logger.error(f"Unexpected pipeline error: {e}", exc_info=True)
        answer = "⚠️ An internal error occurred. Please try again."

    elapsed = time.time() - start

    print(f"\n🤖 Assistant:\n{answer}")
    print(f"\n⏱️  Response time: {elapsed:.2f}s")

    # ── Update rolling history ───────────────────────────────
    conversation_history.append(HumanMessage(content=user_input))
    conversation_history.append(AIMessage(content=answer))

    max_msgs = MAX_HISTORY_TURNS * 2          # each turn = 1 Human + 1 AI
    if len(conversation_history) > max_msgs:
        conversation_history = conversation_history[-max_msgs:]