# -*- coding: utf-8 -*-
"""practice

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13QLorsJX5YMoYhbjLfvXDbkcmW5t6w9e
"""

!pip install langchain_groq

from langchain_groq import ChatGroq

model = ChatGroq(
    model_name = 'llama-3.1-8b-instant',
    api_key= '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',
    temperature = 0.1,


)

query = "what is capital of india?"

result = model.invoke(query)
new = result.content
new

#updated