# -*- coding: utf-8 -*-
"""rag

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14GJpmvOO0RkLePzoYCcSBHvadIvsJlEB
"""



api_key = "pcsk_39EGLB_PC9i9y7MQo2FxSqgqdX4akFP3LPFoNqHirwHsicYqAivgQASB4bFsM9ocPY9epZ"

from langchain_huggingface import HuggingFaceEmbeddings
from langchain_groq import ChatGroq

# Initialize embeddings and model
embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

model = ChatGroq(
    model_name="llama-3.1-8b-instant",
    api_key='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'
)

query = "what is langchain?"

# HyDE function - FIXED ✅
def hyde(query):
    prompt = f"""
Write a detailed passage that would likely appear in a document containing the answer to the user's question.

The passage should:
- Include important keywords and terminology.
- Explain the topic clearly and factually.
- Be written in an encyclopedic or technical style.
- Contain information that would help a search system find relevant documents.
- Avoid conversational language.
- Do not mention the question itself.

Question:
{query}

Passage:
"""
    llm_response = model.invoke(prompt)
    # FIXED: Extract content properly ✅
    return llm_response.content

# Get hypothetical document
hypothetical_doc = hyde(query)
print(f"HyDE Generated:\n{hypothetical_doc}\n")

#Great! Let's add **Context Construction** to your RAG pipeline. This technique helps create better context by organizing and enriching the retrieved chunks.

## **Enhanced Code with Context Construction:**


# -*- coding: utf-8 -*-
!pip install streamlit langgraph langgraph-checkpoint-sqlite langchain-core langchain-groq duckduckgo_search sentence-transformers python-dotenv spotipy langchain pinecone pinecone-client pinecone-text langchain-community langchain-openai faiss-cpu numpy pandas matplotlib seaborn scikit-learn requests beautifulsoup4 lxml langchain_huggingface



# Upload and process PDF
from google.colab import files
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from pinecone_text.sparse import BM25Encoder

print("Please upload your PDF file:")
uploaded = files.upload()

pdf_filename = list(uploaded.keys())[0]
print(f"Uploaded: {pdf_filename}")

# Load PDF
loader = PyPDFLoader(pdf_filename)
documents = loader.load()
print(f"Loaded {len(documents)} pages")

# Split with metadata preservation
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=200,
    length_function=len,
)
chunks = text_splitter.split_documents(documents)
print(f"Split into {len(chunks)} chunks")

# Initialize BM25
bm25_encoder = BM25Encoder().default()
texts = [doc.page_content for doc in chunks]
bm25_encoder.fit(texts)
print("✅ BM25 Encoder fitted")



# Pinecone setup
from pinecone import Pinecone, ServerlessSpec
from langchain_community.retrievers import PineconeHybridSearchRetriever

pc = Pinecone(api_key=api_key)
index_name = "langgraph"

if index_name not in pc.list_indexes().names():
    pc.create_index(
        name=index_name,
        dimension=384,
        metric="dotproduct",
        spec=ServerlessSpec(cloud="aws", region="us-east-1")
    )

index = pc.Index(index_name)
print("✅ Pinecone Connected")

# Create and upload vectors with enhanced metadata
vectors = []
for i, (text, doc) in enumerate(zip(texts, chunks)):
    dense_vector = embeddings.embed_query(text)
    sparse_vector = bm25_encoder.encode_documents([text])[0]

    # Enhanced metadata for context construction
    vectors.append({
        "id": str(i),
        "values": dense_vector,
        "sparse_values": sparse_vector,
        "metadata": {
            "context": text,
            "page": doc.metadata.get('page', 0),  # Store page number
            "chunk_id": i,  # Store chunk position
            "source": doc.metadata.get('source', pdf_filename)
        }
    })

index.upsert(vectors=vectors)
print(index.describe_index_stats())

# Initialize retriever
retriever = PineconeHybridSearchRetriever(
    embeddings=embeddings,
    sparse_encoder=bm25_encoder,
    index=index,
    alpha=0.5,
    top_k=7  # Get more for context construction
)

# Retrieve documents
retrieved_docs = retriever.invoke(hypothetical_doc)
print(f"\n✅ Retrieved {len(retrieved_docs)} documents")

# ========================================
# CONTEXT CONSTRUCTION 🎯
# ========================================

import numpy as np
from sentence_transformers import CrossEncoder

def construct_context(retrieved_docs, top_k=3, score_threshold=0.0, max_tokens=2000):
    """
    Advanced context construction with multiple strategies:
    1. Ranking/Threshold    - Filter by relevance score
    2. Deduplication        - Remove similar chunks
    3. Context Compression  - Manage token/context window
    4. Source Balancing     - Fair representation across sources
    5. Ordering             - Sort by page/position for coherence
    6. Formatting           - Structure for better LLM comprehension
    """

    # ─────────────────────────────────────────
    # Extract documents with metadata
    # ─────────────────────────────────────────
    docs_with_metadata = []
    for doc in retrieved_docs:
        docs_with_metadata.append({
            'content': doc.page_content,
            'page': doc.metadata.get('page', 0),
            'chunk_id': doc.metadata.get('chunk_id', 0),
            'source': doc.metadata.get('source', 'unknown'),
            'score': doc.metadata.get('score', 0.0)
        })

    # ─────────────────────────────────────────
    # Strategy 1: Score Threshold Filtering
    # ─────────────────────────────────────────
    def filter_by_score(docs, threshold=0.0):
        """
        Remove chunks below relevance score threshold.
        Prevents low-quality chunks from polluting context.
        threshold=0.0 means keep all (default safe value)
        """
        if threshold <= 0.0:
            return docs

        filtered = [
            doc for doc in docs
            if doc.get('score', 0.0) >= threshold
        ]

        print(f"Score filtering: {len(docs)} → {len(filtered)} chunks "
              f"(threshold={threshold})")
        return filtered

    # ─────────────────────────────────────────
    # Strategy 2: Deduplication
    # ─────────────────────────────────────────
    def deduplicate(docs, threshold=0.8):
        """
        Remove chunks that are too similar using
        Jaccard similarity on word overlap.
        threshold=0.8 means 80% word overlap = duplicate
        """
        unique_docs = []

        for doc in docs:
            is_unique = True

            for unique_doc in unique_docs:
                content1 = set(doc['content'].lower().split())
                content2 = set(unique_doc['content'].lower().split())

                if len(content1) == 0 or len(content2) == 0:
                    continue

                overlap = len(content1 & content2) / len(content1 | content2)

                if overlap > threshold:
                    is_unique = False
                    # Keep the higher scored chunk
                    if doc.get('score', 0) > unique_doc.get('score', 0):
                        unique_docs.remove(unique_doc)
                        unique_docs.append(doc)
                    break

            if is_unique:
                unique_docs.append(doc)

        print(f"Deduplication: {len(docs)} → {len(unique_docs)} unique chunks")
        return unique_docs

    # ─────────────────────────────────────────
    # Strategy 3: Context Window Management
    # ─────────────────────────────────────────
    def manage_context_window(docs, max_tokens=2000):
        """
        Ensure total context fits within token limit.
        Approximation: 1 token ≈ 4 characters
        Compress long chunks by keeping first N characters.
        """
        MAX_CHARS = max_tokens * 4
        CHUNK_MAX_CHARS = MAX_CHARS // max(len(docs), 1)

        managed_docs = []
        total_chars = 0

        for doc in docs:
            content = doc['content'].strip()

            # Compress individual chunk if too long
            if len(content) > CHUNK_MAX_CHARS:
                # Keep most important part (beginning)
                content = content[:CHUNK_MAX_CHARS]
                # Cut at last complete sentence
                last_period = content.rfind('.')
                if last_period > CHUNK_MAX_CHARS * 0.5:
                    content = content[:last_period + 1]
                content = content + " [truncated]"

            # Check total budget
            if total_chars + len(content) > MAX_CHARS:
                print(f"Context window limit reached at chunk {len(managed_docs) + 1}")
                break

            doc_copy = doc.copy()
            doc_copy['content'] = content
            managed_docs.append(doc_copy)
            total_chars += len(content)

        print(f"Context window: {len(docs)} → {len(managed_docs)} chunks "
              f"({total_chars} chars / ~{total_chars // 4} tokens)")
        return managed_docs

    # ─────────────────────────────────────────
    # Strategy 4: Source Balancing
    # ─────────────────────────────────────────
    def balance_sources(docs, max_per_source=2):
        """
        Prevent one source from dominating the context.
        Example: If top_k=6 and all chunks are from page 1,
        the answer will be biased toward page 1 content only.
        max_per_source=2 means max 2 chunks per unique source.
        """
        source_counts = {}
        balanced_docs = []

        for doc in docs:
            source = doc.get('source', 'unknown')
            count = source_counts.get(source, 0)

            if count < max_per_source:
                balanced_docs.append(doc)
                source_counts[source] = count + 1
            else:
                print(f"Source balance: Skipping extra chunk from '{source}'")

        print(f"Source balancing: {len(docs)} → {len(balanced_docs)} chunks")
        print(f"Source distribution: {source_counts}")
        return balanced_docs

    # ─────────────────────────────────────────
    # Strategy 5: Sort by Position
    # ─────────────────────────────────────────
    def sort_by_position(docs):
        """Sort documents by page number and chunk position"""
        return sorted(docs, key=lambda x: (x['page'], x['chunk_id']))

    # ─────────────────────────────────────────
    # Strategy 6: Get Surrounding Chunks
    # ─────────────────────────────────────────
    def expand_context(doc, all_chunks, window=1):
        """Get neighboring chunks for more context"""
        chunk_id = doc['chunk_id']
        page = doc['page']

        expanded = [doc]

        # Get previous chunk if on same page
        if chunk_id > 0:
            prev_chunk = all_chunks[chunk_id - 1] if chunk_id - 1 < len(all_chunks) else None
            if prev_chunk and prev_chunk.metadata.get('page') == page:
                expanded.insert(0, {
                    'content': prev_chunk.page_content,
                    'page': prev_chunk.metadata.get('page', 0),
                    'chunk_id': prev_chunk.metadata.get('chunk_id', 0),
                    'source': prev_chunk.metadata.get('source', 'unknown'),
                    'score': 0.0,
                    'position': 'before'
                })

        # Get next chunk if on same page
        if chunk_id < len(all_chunks) - 1:
            next_chunk = all_chunks[chunk_id + 1]
            if next_chunk.metadata.get('page') == page:
                expanded.append({
                    'content': next_chunk.page_content,
                    'page': next_chunk.metadata.get('page', 0),
                    'chunk_id': next_chunk.metadata.get('chunk_id', 0),
                    'source': next_chunk.metadata.get('source', 'unknown'),
                    'score': 0.0,
                    'position': 'after'
                })

        return expanded

    # ─────────────────────────────────────────
    # Apply All Strategies in Order
    # ─────────────────────────────────────────

    print("\n" + "="*50)
    print("CONTEXT CONSTRUCTION PIPELINE")
    print("="*50)
    print(f"Input: {len(docs_with_metadata)} chunks")

    # Step 1: Score threshold filtering
    filtered_docs = filter_by_score(docs_with_metadata, threshold=score_threshold)

    # Step 2: Deduplicate
    unique_docs = deduplicate(filtered_docs, threshold=0.8)

    # Step 3: Source balancing
    balanced_docs = balance_sources(unique_docs, max_per_source=2)

    # Step 4: Take top K
    top_docs = balanced_docs[:top_k]
    print(f"Top-K selection: keeping {len(top_docs)} chunks")

    # Step 5: Context window management
    managed_docs = manage_context_window(top_docs, max_tokens=max_tokens)

    # Step 6: Sort by position
    sorted_docs = sort_by_position(managed_docs)

    # Step 7: Format context
    formatted_context = []
    for i, doc in enumerate(sorted_docs, 1):
        score_str = f"{doc['score']:.4f}" if doc.get('score', 0) > 0 else "N/A"
        source_str = doc.get('source', 'unknown')

        formatted_context.append(
            f"[Document {i} | Page {doc['page']} | "
            f"Source: {source_str} | Score: {score_str}]\n"
            f"{doc['content']}"
        )

    print(f"\nFinal context: {len(sorted_docs)} chunks")
    print("="*50)

    return "\n\n---\n\n".join(formatted_context), sorted_docs


# ========================================
# RERANKING with Context Construction
# ========================================

reranker = CrossEncoder('cross-encoder/ms-marco-MiniLM-L-6-v2')

# Extract text content from documents
doc_texts = [doc.page_content for doc in retrieved_docs]

# Score each query-document pair
pairs = [[hypothetical_doc, doc_text] for doc_text in doc_texts]
scores = reranker.predict(pairs)

# Rerank
ranked = sorted(zip(scores, retrieved_docs), key=lambda x: x[0], reverse=True)

print("\n=== Reranked Results ===")
for i, (score, doc) in enumerate(ranked[:5], 1):
    print(f"\n{i}. Score: {score:.4f} | Page: {doc.metadata.get('page', 'N/A')}")
    print(f"Content: {doc.page_content[:150]}...")

# ─────────────────────────────────────────
# Pass scores into metadata before
# context construction
# ─────────────────────────────────────────
top_docs_for_context = []
for score, doc in ranked[:5]:
    doc.metadata['score'] = float(score)
    top_docs_for_context.append(doc)

# Apply context construction to top documents
constructed_context, sorted_docs = construct_context(
    top_docs_for_context,
    top_k=3,
    score_threshold=0.0,
    max_tokens=2000
)

print("\n" + "="*60)
print("CONSTRUCTED CONTEXT:")
print("="*60)
print(constructed_context[:500] + "...")

# ========================================
# GENERATE FINAL ANSWER with Constructed Context
# ========================================

def generate_answer(query, constructed_context):

    prompt = f"""
You are an expert retrieval-augmented AI assistant.

Your task is to answer the user's question using ONLY the information provided in the retrieved context.

Rules:

1. Grounding
- Use only facts found in the context.
- Do not use outside knowledge.
- Do not infer facts that are not explicitly supported by the context.
- If the context is insufficient, state:
  "I don't have enough information in the provided context to answer this question."

2. Answer Quality
- Provide a complete and accurate answer.
- Combine information from multiple context passages when relevant.
- Remove redundant or repeated information.
- Do not copy large portions of the context verbatim.
- Synthesize information into a coherent explanation.

3. Structure
- Start with a direct answer.
- Then provide supporting details.
- Use bullet points or numbered lists when helpful.
- Keep the answer clear and concise.
- Use simple language unless the question requires technical detail.

4. Handling Conflicts
- If multiple context passages contain conflicting information,
  mention the conflict and present both viewpoints.
- Do not choose a side unless the context clearly supports it.

5. Citations
- When source identifiers are available, cite them inline.
- Example: [Document 2], [Page 5], [Section: Retrieval].

Question:
{query}

Retrieved Context:
{constructed_context}

Answer:
"""

    response = model.invoke(prompt)
    return response.content

# Generate final answer
final_answer = generate_answer(query, constructed_context)

print("\n" + "="*60)
print("FINAL ANSWER:")
print("="*60)
print(final_answer)
print("="*60)

# Optional: Show which documents were used
print("\n📚 Documents used in answer:")
for i, doc in enumerate(sorted_docs, 1):
    print(f"{i}. Page {doc['page']} - Chunk {doc['chunk_id']}")