# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CyqLRi36a-79hOmHBADAtEXEAr_qAbUa
"""

!pip install streamlit langgraph langgraph-checkpoint-sqlite langchain-core langchain-groq duckduckgo_search sentence-transformers python-dotenv spotipy langchain pinecone pinecone-client pinecone-text langchain-community langchain-openai faiss-cpu numpy pandas matplotlib seaborn scikit-learn requests beautifulsoup4 lxml

api_key = "pcsk_39EGLB_PC9i9y7MQo2FxSqgqdX4akFP3LPFoNqHirwHsicYqAivgQASB4bFsM9ocPY9epZ"

!pip install langchain_huggingface

from langchain_huggingface import HuggingFaceEmbeddings

!pip install sentence-transformers

from langchain_huggingface import HuggingFaceEmbeddings

# This runs locally, no API needed
embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

from langchain_groq import ChatGroq

model = ChatGroq(
    model_name = "llama-3.1-8b-instant",
    api_key = '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'
)

!pip install pypdf langchain-text-splitters

query = str("what is langchain?")

def hyde(query):

  prompt = f"""
  Write a detailed passage that would likely appear in a document containing the answer to the user's question.

  The passage should:
  - Include important keywords and terminology.
  - Explain the topic clearly and factually.
  - Be written in an encyclopedic or technical style.
  - Contain information that would help a search system find relevant documents.
  - Avoid conversational language.
  - Do not mention the question itself.

  Question:
  {query}

  Passage:
  """
  llm = model.invoke(prompt)
  new_query = llm

  return new_query

hii = str(hyde(query))

# Upload PDF file
from google.colab import files
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from pinecone_text.sparse import BM25Encoder

print("Please upload your PDF file:")
uploaded = files.upload()

# Get filename
pdf_filename = list(uploaded.keys())[0]
print(f"Uploaded: {pdf_filename}")

# Step 1: Load PDF
loader = PyPDFLoader(pdf_filename)
documents = loader.load()

print(f"Loaded {len(documents)} pages from the PDF")
print(f"First page preview:\n{documents[0].page_content[:200]}...")

# Step 2: Split documents into chunks
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=200,
    length_function=len,
)

chunks = text_splitter.split_documents(documents)

print(f"Split into {len(chunks)} chunks")

# Step 3: Initialize and fit BM25 Encoder
bm25_encoder = BM25Encoder().default()

# Fit BM25 on the chunk texts
texts = [doc.page_content for doc in chunks]
bm25_encoder.fit(texts)

print("✅ BM25 Encoder fitted on corpus")

from langchain_community.retrievers import PineconeHybridSearchRetriever
import os
from pinecone import Pinecone, ServerlessSpec


pc = Pinecone(api_key = api_key)

index_name = "langgraph"

if index_name not in pc.list_indexes().names():
    pc.create_index(
        name=index_name,
        dimension=384,
        metric="dotproduct",
        spec=ServerlessSpec(
            cloud="aws",
            region="us-east-1"
        )
    )

# Connect to Index
index = pc.Index(index_name)
print("✅ Pinecone Connected Successfully!")

from langchain_community.retrievers import PineconeHybridSearchRetriever
from pinecone import Pinecone
from pinecone_text.sparse import BM25Encoder
from langchain_community.embeddings import HuggingFaceEmbeddings

vectors = []

for i, text in enumerate(texts):

    dense_vector = embeddings.embed_query(text)

    sparse_vector = bm25_encoder.encode_documents([text])[0]

    vectors.append({
    "id": str(i),
    "values": dense_vector,
    "sparse_values": sparse_vector,
    "metadata": {
        "context": text
    }
})

# ==========================
# Store in Pinecone
# ==========================

index.upsert(vectors=vectors)

print(index.describe_index_stats())

# ==========================
# Hybrid Retriever
# ==========================

retriever = PineconeHybridSearchRetriever(
    embeddings=embeddings,
    sparse_encoder=bm25_encoder,
    index=index,
    alpha=0.5,
    top_k=3
)

"""# ==========================
# Search
# ==========================

results = retriever.invoke("himmu")

for i, doc in enumerate(results, 1):
    print(f"\nResult {i}")
    print(doc.page_content[:500])"""

results = str(retriever.invoke(hii))

from sentence_transformers import CrossEncoder

reranker = CrossEncoder('cross-encoder/ms-marco-MiniLM-L-6-v2')



# Score each query-document pair
pairs = [[hii, doc] for doc in results]
scores = reranker.predict(pairs)

# Rerank
ranked = sorted(zip(scores, results), reverse=True)
for score, doc in ranked:
    print(f"Score: {score:.4f} | {doc[:50]}")

def better_ans(ranked):

  prompt = prompt = f"""
  You are a knowledgeable assistant.

  Using only the information provided in the retrieved context, generate a clear, accurate, and well-organized answer.

  Instructions:
  - Explain the topic in simple and understandable language.
  - Organize the answer logically.
  - Include important details and key concepts.
  - If appropriate, use bullet points or numbered steps.
  - Combine information from multiple context passages into a single coherent explanation.
  - Do not repeat the same information.
  - If the context does not contain enough information, say so.
  - Do not make up facts that are not present in the context.

  Context:
  {ranked}
  """
  new_llm = model.invoke(prompt)
  new_result = new_llm

  return new_result

# After reranking, keep only top 3
ranked = sorted(zip(scores, results), reverse=True)
top_3 = ranked[:3]

# Then call
new_ans = better_ans(top_3)

print(new_ans)

print(type(model))

